platform android
platformName Android
automationName uiautomator2
deviceName RedMi A4 5G
udid 89f0fd14
autoGrantPermissions true
ignoreHiddenApiPolicyError true
noReset true
appPackage io.appium.android.apis
appActivity .ApiDemos
